name: Deploy to CIS web server

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    adjust_urls:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v3
             with:
                fetch-depth: 0  # need a full history (otherwise merge won't work)
           - run: git config user.name github-actions
           - run: git config user.email github-actions@github.com  
           - run: git fetch origin cis  # action only fetches one branch.  We need to fetch the other explicitly
           - run: git checkout --progress --force -B cis refs/remotes/origin/cis
           - run: git merge main
           - uses: jacobtomlinson/gha-find-replace@v2
             with: 
                find: "http://localhost:8000"
                replace: "https://faculty.computing.gvsu.edu/kurmasz/"
                regex: false                   
           - run: git add -- . ':!.github'  # the replace action will modify line 20 above. Don't add/commit that change
           - run: git commit -m 'substitute URLs for CIS server'
           - run: git push
    
